
stages:
  - build
  - unit

cache:
  paths:
    - node_modules/

build:
  image: node:latest
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

unit:
  stage: unit
  script:
    - yarn --frozen-lockfile
    - yarn test-proto
    - yarn unit
    - yarn diff:sample-json
